name: gendiff_actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip install poetry
          make install
          pip install coverage
          pip install pytest-cov
      - run: make lint
      - run: make test
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true