name: gendiff_actions

on:
    push:
        branches:
            - '**'
        tags:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v3
            - name: Install Dependencies
              run: |
                pip install poetry
                make install
            - run: make lint
            - run: make test

              