name: gendiff_actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install  Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          make install

      - name: Lint the code
        run: |
          make lint

      - name: Run tests
        run: |
          make test
